#!/bin/sh


#Variables
CONFIG="${HOME}/src/dotfiles"
GIT="/usr/bin/git"

#Exported Variables
export GNUPGHOME="/root/.local/share/gnupg"

#Main
cd "${CONFIG}" || return
if ("${GIT}" fetch origin +master && "${GIT}" verify-commit origin/master)
then
  "${GIT}" reset --hard origin/master
fi
